### ISSUE TITLE
[BUG] Frontend says "something went wrong while fetching"

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#109]
**Describe the bug**
There seems to be some problem with the api connection

**Screenshots**
<img width="1920" alt="Screenshot 2020-10-09 at 7 10 17 PM" src="https://user-images.githubusercontent.com/40575379/95590198-6061e300-0a63-11eb-96e5-c97586321000.png">
<img width="1920" alt="Screenshot 2020-10-09 at 7 12 43 PM" src="https://user-images.githubusercontent.com/40575379/95590233-6f489580-0a63-11eb-8892-bc060ba47849.png">

**Comment by sahilnanda1995** [comment]
fixed in recent merge
