### ISSUE TITLE
[BUG] App breaks when redirecting to overview after successful transaction

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#124]
**Describe the bug**
App breaks when redirecting to overview after successful transaction

<img width="1920" alt="Screenshot 2020-10-30 at 7 25 24 PM" src="https://user-images.githubusercontent.com/40575379/97713433-d4812b00-1ae5-11eb-9114-c5741ab15f08.png">

**Comment by sahilnanda1995** [comment]
fixed in the recent merge
