### ISSUE TITLE
[BUG] Display "total balance" instead of "Transferrable Balance" on header

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#131]
**Describe the bug**
The current implementation of YieldScan displays "transferrable balance" on the header. This has no use on the platform at the moment, and even if we add a feature to transfer tokens in the future, it should be implemented in a similar way to "invest more"/"withdraw" modals on overview, rather than globally.

As of now, it just causes confusion on the reward calculator, where I'm able to enter amounts larger than my "transferrable balance".

**Expected behavior**
Display total balance on the header.

**Screenshots**
<img width="1920" alt="Screenshot 2020-11-24 at 4 34 28 PM" src="https://user-images.githubusercontent.com/40575379/100086176-0aaa9400-2e73-11eb-8ea0-8d7c0fd3569c.png">

**Comment by prastut** [comment]
@saumyakaran please don't assign issues to anyone at the moment. It will cause confusion as to whether we have to do it now.

I know you placed priority order but still.

**Comment by saumyakaran** [comment]
@prastut Got it. Cleared assignees.
