### ISSUE TITLE
[BUG] PolkadotJS authorization prompt popups up without triggering wallet connect

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#133]
**Describe the bug**
PolkadotJS authorization prompt popups up without triggering wallet connect ([see video](https://file.video/v/4ebb8fe9-1512-49db-847d-f6907da199b7) for clarity - as soon as I visit the website, I am prompted by default)

**To Reproduce**
Visit yieldscan using a browser which has PolkadotJS extension installed, but hasn't yet accepted/rejected the PolkadotJS auth prompt

**Expected behavior**
The prompt should only appear when user triggers wallet connect using one of the "Connect Wallet" buttons.

**Comment by prastut** [comment]
Crucial for launch. Assigning Sahil.
