### ISSUE TITLE
[FEATURE REQUEST] Inform user about how to re-authorize if PolkadotJS prompt is rejected

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#135]
**Is your feature request related to a problem? Please describe.**
User isn't informed about how to re-authorize if they reject the PolkadotJS auth prompt.

**Describe the solution you'd like**
User should be informed that they can simply quit and relaunch the browser to authorize their wallet.

**Comment by sahilnanda1995** [comment]
Duplicate #144
