### ISSUE TITLE
[BUG] Memory leak in reward calculator

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#146]
**Describe the bug**
Memory leak in reward calculator

**To Reproduce**
1. Go to calculator page then visit any other page on the platform
2. The error will be logged in browser console

**Screenshots**
<img width="567" alt="Screenshot 2020-11-28 at 5 37 32 PM" src="https://user-images.githubusercontent.com/40575379/100515239-92a8da80-31a0-11eb-96fa-d7a53af17df2.png">

**Comment by prastut** [comment]
@sahilnanda1995 how was this fixed? Curious.

**Comment by sahilnanda1995** [comment]
this was caused because of merging this [PR](https://github.com/buidl-labs/yieldscan-frontend/pull/140) without testing, just reverted it for the fix
