### ISSUE TITLE
[BUG] Earnings should be zero for zero time period

### ISSUE THREAD

**Issue by sahilnanda1995** [buidl-labs/yieldscan-frontend#169]
**Describe the bug**

on the rewards calculator page the earnings are non-zero for no time period

**To Reproduce**
1. Go to https://yieldscan.onrender.com/reward-calculator
2. set time period input to  0
4. See Earnings card

**Expected behavior**

Earnings card should display all the earnings as zero

**Screenshots**

![image](https://user-images.githubusercontent.com/41546731/101281628-180e3980-37f6-11eb-868a-2dffb3076f66.png)

**Comment by prastut** [comment]
Shouldn't 0 be never an option?

**Comment by sahilnanda1995** [comment]
> Shouldn't 0 be never an option?

Yeah, that should be the case(which leads to more complex solution and also raises other cases that would be needed to handle) but for now i think solving only this would be more optimal, probably should make an issue for this to tackle in future.
