### ISSUE TITLE
[BUG] "Tweet APR" CTA's content is outdated

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#171]
Content change to:

```
I'm earning 17.83% APR by staking on @Polkadot through @yield_scan - created by @buidllabs. What are you waiting for?

Stake on https://yieldscan.onrender.com/ and be a part of @Polkadot & @kusamanetwork today!

Don't forget to tweet your APR! #YieldScan $DOT $KSM
```

**Ensure that the following is done:**
- [x] Change `@polkadotnetwork` -> `@Polkadot` (and ensure that it changes with network change i.e. `@kusamanetwork` for Kusama and `@Polkadot` for Polkadot)
- [x] Line breaks are consistent with the content above

**Comment by sahilnanda1995** [comment]
@saumyakaran i think this is too many mentions: `Stake on https://yieldscan.onrender.com/ and be a part of @Polkadot & @kusamanetwork today!`
we should change it to something like this `Stake on https://yieldscan.onrender.com/ and be a part of network today!`

**Comment by saumyakaran** [comment]
> i think this is too many mentions

That's actually intentional -> from my discussion with @prastut regarding mentions creating network effects -> i.e. we tweet, they see, they retweet, we leverage their audience as well.
