### ISSUE TITLE
Setup codebase

### ISSUE THREAD

**Issue by akshatbhargava123** [buidl-labs/yieldscan-frontend#2]
- [x] Init a NextJS codebase
- [x] Setup TailwindCSS
- [ ] Setup linting (eslint + airbnb) and pre-commit hooks
- [x] Add Path aliasing
- [x] Create common `Page` HOC
- [x] Create layout providing mechanism
- [x] Polkadot API single instance implementation
- [x] Make Polkadot extension API data available

**Comment by saumyakaran** [comment]
@akshatbhargava123 Would it make sense to close this issue and create a separate issue for linting and assign it appropriate labels for priority, size, etc.?

**Comment by akshatbhargava123** [comment]
closing this now, moved linting concern to https://github.com/buidl-labs/yieldscan-frontend/issues/13.
