### ISSUE TITLE
[BUG] Wallet connected calculation discrepancy

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#39]
**Describe the bug**

**To Reproduce**
1. Go to 'https://yieldscan.onrender.com/reward-calculator'
2. Connect wallet
3. Input time period and stake amount and select risk level
4. See the calculated results

**Expected behavior**

The estimated yield seems to be using the "bond additional funds" input to calculate the returns, when in fact I expect the "total staking amount" to be used for calculation.

**Screenshots**

![Screenshot 2020-07-23 at 10 31 40 AM](https://user-images.githubusercontent.com/40575379/88253540-ed509800-cccf-11ea-90a7-0db4e2fc4735.png)

**Additional context**

N.A.

**Comment by akshatbhargava123** [comment]
Fixed in #38 .
