### ISSUE TITLE
[BUG] Email and Riot handles aren't displayed on profiles for validators, council members and runner ups

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#62]
**Describe the bug**
Email and Riot handles aren't displayed on profiles for validators, council members and runner ups

**To Reproduce**
Visit: https://yieldscan.onrender.com/council-member-profile/FcxNWVy5RESDsErjwyZmPCW6Z8Y3fbfLzmou34YZTrbcraL

**Expected behavior**
I would like to see email, web link, riot as well as twitter info for validators, council members and runner ups 

**Screenshots**
<img width="1440" alt="Screenshot 2020-08-05 at 4 39 03 PM" src="https://user-images.githubusercontent.com/40575379/89406320-9cfb2080-d73a-11ea-90b1-293c3dadbf90.png">
<img width="1440" alt="Screenshot 2020-08-05 at 4 42 23 PM" src="https://user-images.githubusercontent.com/40575379/89406373-b13f1d80-d73a-11ea-953e-eefb93b0c5d6.png">

**Additional information**
- How the riot info will be displayed is still a design problem (refer [this figma comment](https://www.figma.com/file/n65zoIVgwL847PMyerqkLx?node-id=1717:22445#35758143))

**Comment by sahilnanda1995** [comment]
added
