### ISSUE TITLE
Try to adopt as much functional programming patterns as possible

### ISSUE THREAD

**Issue by prastut** [buidl-labs/yieldscan-frontend#7]
I noticed non-functional patterns in code: https://github.com/buidl-labs/yieldscan-frontend/blob/master/lib/calculate-reward.js#L22

Though we didn't commit on following a functional pattern, I would suggest we do so. Saves a lot of hassle down the road due to having immutability has a north star. 

See more here: https://github.com/airbnb/javascript#iterators--nope

**Comment by akshatbhargava123** [comment]
@prastut I agree with your concern, tried to follow such best practices at most places but might have missed at some due to the hustle of shipping, thanks for getting this in light. :)
Please feel free to share other quality-related problems you feel we have, I'll be more than happy to take in a review. ⭐

**Comment by saumyakaran** [comment]
@prastut Could you please assign a priority to this issue (ideally all issues opened by you)?

**Comment by prastut** [comment]
@akshatbhargava123 

> missed at some

Probably this is the root cause. You don't need to remember, I think eslint + Airbnb style guide keeps telling you while you write code in VSCode and code automatically starts getting better inch by inch.

**Comment by prastut** [comment]
@saumyakaran assigned to all in this repo: https://github.com/buidl-labs/yieldscan-frontend/issues/created_by/prastut

**Comment by akshatbhargava123** [comment]
> eslint + Airbnb style guide keeps telling you while you write code in VSCode
This is already taken into consideration under #2 which I did not assign time to, after diving into the ecosystem. 😅 
Will take this into top priority after all [P1] issues are solved in the next 2-day sprint.
Shall I close this issue since it's a duplicate at this point?

**Comment by akshatbhargava123** [comment]
closing this now, moved concern to: https://github.com/buidl-labs/yieldscan-frontend/issues/13
