### ISSUE TITLE
[BUG] Error "1002" when trying to stake

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#70]
**Describe the bug**

I'm unable to complete the staking transaction due to the following error:

```2020-08-11 12:45:04        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum Call: RuntimeApi("Execution: Could not convert parameter `tx` between node and runtime: No such variant in```

**To Reproduce**
Simply tried to stake with my id `Eksmah4LfMN3wbVggUxftDnFr8J2sGhKUV84Yw7QHsox1iN` on Kusama using the returns calculator.

Preferences Used:
- No additional funds to bond
- Medium risk
- 12 months time
- Compounding on

Followed the flow to the end step, where after signing transaction it keeps on failing with the same error "1002".

**Expected behavior**
I expected the transaction to be successfully sent to the chain.

**Screenshots**
The same error is logged 3 times, because I tried it multiple times to be sure:
<img width="1440" alt="Screenshot 2020-08-11 at 12 46 39 PM" src="https://user-images.githubusercontent.com/40575379/89868717-e6cb8700-dbd0-11ea-893c-65dcaca690eb.png">

**Comment by shixm1102** [comment]
I'm unable to complete the transfer transaction due to this error When I separate the signature transaction from the send transaction

**Comment by shixm1102** [comment]
I'm unable to complete the transfer transaction due to this error when I separate the signature transaction from the send transaction

**Comment by saumyakaran** [comment]
@shixm1102 Could you tell me what URL are you using for transferring tokens?
