### ISSUE TITLE
[BUG] State management issue with Returns Calculator

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#74]
**Describe the bug**
When I enter any amount on the  “already bonded” ux then visit the confirmation page, the amount is reduced due to some reason - i.e. it’s not the same as “total staking amount” on the returns calculator.

**Expected behavior**
I expect the amount shown in the confirmation page to be the same as the "total staking amount" on the previous page + it shouldn't reduce everytime I click the "back" button.

**Comment by prastut** [comment]
@saumyakaran add screenshots/loom video. Gives visibility of the bug.

**Comment by saumyakaran** [comment]
Video that describes the bug: https://www.loom.com/share/1f184f9099d7456f9f3e7608d9c46899
