### ISSUE TITLE
[BUG] Wallet connection multiple modals open

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#75]
**Describe the bug**
After connecting the PolkadotJS extension, 2 modals are open simultaneously, one behind the other.

**To Reproduce**
1. Go to the yieldscan and click on "Connect wallet" button on the navbar or from the CTA on returns calculator.
2. Click on "connect my wallet" in the modal that opens up.
3. Once you authorize from the extension, the popup that opens up next is on top of the previous one.

**Expected behavior**
There should only be 1 popup open at a time.

**Screenshots**
<img width="1440" alt="Screenshot 2020-08-17 at 11 08 19 AM" src="https://user-images.githubusercontent.com/40575379/90361027-cb51f780-e07a-11ea-9ce3-96047c9cce12.png">

**Addition information**

- At the time of writing this, the latest branch I was using was [fixes/ui](https://github.com/buidl-labs/yieldscan-frontend/tree/fixes/ui)

**Comment by sahilnanda1995** [comment]
fixed
