### ISSUE TITLE
[UX Feedback] Staking user flow

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#8]
## Global feedback

- [x] [+P2] I need to re-authenticate and re-select my account on reloading, even though I already granted access + selected my preference for the account. I would like that to be **stored for the current session**
- [x] [+P2] The currency should **NOT** be hard-coded (**both** **fiat** and the **crypto**)
    - The crypto currency will **change based on network selection**
    
- [ ] [+P3] All numbers should be formatted based on localization

### Top Navbar

- [x] [+P1] I have no indication about which network I'm on (Kusama or Polkadot)
    - [ ] [+P2] Also, I want to be able to **choose between the networks** - this might not be available from the backend yet, so a placeholder will work
- ~~Connect wallet button on the navbar doesn't work~~
- [x] [+P2, CRITICAL] When wallet is connected, there's no way for me to **switch my stash account globally**

### Right-side Content

1. Staking amount
    - [x] [+P1] Free balance is shown even when I don't have my account connected - this confuses me
    - [x] [+P2] Hovering on "KSM" button turns the cursor to pointer but nothing happens on click - if it's not supposed to do anything, the cursor shouldn't change
    - **When authenticated:**
        - [x] [+P1, CRITICAL ] If my funds are already bonded, then I would prefer to have the advanced UI that Abhinav has designed for the staking amount input
        - [x] [+P1, CRITICAL] If I make changes to the calculator input like staking amount, risk preference, etc. before connecting my wallet, I would want my preferences to be stored after connection as well, so I can continue where I left off
            - The staking amount in such a scenario is critical to get right - I would want my previous input to become the `total_staking_amount` and would want the new input for `bond_additional_funds` to be adjusted accordingly
            - NOTE: `total_staking_amount = bond_additional_funds + currently_bonded`
            - Ignore the un-bonding case for now (add this to a later TODO)
        - [x] [+P2, CRITICAL] I would also want the UI to prompt me if I go above my free balance and not allow me to stake
2. Risk preference
    - ~~I would prefer to have a default selection for risk score~~
3. Expected results
    - [x] [+P3] Default state (i.e. when there's no input) is better being "-" than "?"
    - [x] [+P1] The expected results say that if I invest a $1000 today, I'll be millionaire in 10 years 🤑 - as much as I would like to believe that, it won't happen this way
    - [x] [+P2, CRITICAL] PS - There seems to be some problem with the estimated portfolio value as well - the following is the logic to be followed `estimated_portfolio_value = already_bonded + staking_amount + estimated_returns`
4. Suggested validators
    - [x] [+P2, CRITICAL] Just selecting the risk score gives me the list of suggested validators - I would like to complete all my inputs before receiving the suggestions and the expected results
    - [x] [+P2] The validators don't have individual returns associated with them, I would like to see how much rewards each validator will earn for me

## Wallet connection popup

- [x] [+P2] Once I have authorized the wallet, it no longer makes sense to show me the same popup - since you already have access to my accounts (probably storing session will rectify this)
- [x] [+ ~P1~ P2, CRITICAL] For the stash selection (both in **wallet connect popup** and in **navbar**), we should NOT display controllers, i.e. display only unassigned (accounts with no previous bonds) or stash accounts. To check which accounts to display:
    1. Checking if the account is **stash**
        - Using the `staking.bonded` api call will confirm if the account is a stash
    2. Checking if the account is **controller** - **DO NOT DISPLAY**
        - Using the `staking.ledger` api call will confirm if the account is a controller
    3. Checking if the account is **unassigned**
        - If both `staking.bonded` and `staking.ledger` return `none`, then the account is unassigned

## Payment confirmation view

- [x] [+P2, CRITICAL] Add back button on the payment UX

### Confirmation step

- [x] [+P1] If I have **NO previously bonded funds**, I wouldn't want to be over-loaded with unnecessary info like `currently_bonded` and `additional_funds_to_bond`. Instead, I would prefer to just have my `total_amount` displayed to me

### Reward destination selection [+P1]

- [x] `riskScore` in validator table not right values mapped to validators.
- [x] If **compounding is** **true**, then I don't have a choice, in which case I would simply want to be displayed the account where the rewards will be received (i.e. stash)
- [x] If **compounding is false**, then the current UX works, although I would like to have a **button to either "skip" or "use default"** for users who find the decision to be confusing

### Payment step
[+P3, CRTICAL]
Breaking this into 2 scenarios:

1. User has **NO previous bonds** **OR** User has a previous bond, but is using the **SAME account** for stash and controller
    - Current UX works well
    - However, when I click "edit controller", I would like an account to show up below the stash which looks the same as stash (on the UI level) and says controller (the account being used by default will be the same as stash). On the UI element I'd like to have the edit button (maybe use the pen icon?) which opens the popup which allows me to select a controller.
        - **NOTE:** In the popup, I should only be shown the unassigned accounts (since stashes can't be used as controller and existing controllers have a 1:1 relation with stash)
2. User has a previous bond and is using **DISTINCT accounts** for stash and controller
    - Here, we can show both the accounts on the UI directly and do away with the "edit controller" button and allow the user to edit the controller using a similar popup as described above.
        - **NOTE:** In this popup, along with unassigned accounts, we also need to display the controller account which is currently being used (which would also be the default selection)

- [x] [+P1, CRITICAL] Handle transaction success/error state correctly, ONLY show the correct status as of now (proper custom error handling TBD later).

**Comment by saumyakaran** [comment]
@akshatbhargava123 I'm receiving a "success" toast, even though the transaction was actually rejected by the chain - might want to look into this as well

![image](https://user-images.githubusercontent.com/40575379/85112515-59546200-b233-11ea-8c60-863992c0b54a.png)

**Comment by akshatbhargava123** [comment]
@saumyakaran ETA for all `+P1` points: 22nd June, Monday - EOD

**Comment by saumyakaran** [comment]
@akshatbhargava123 Following up on our discussion about payment UX back button, @AbhinavThukral97 correctly pointed out that having the back button is important in our case due to the novel nature of our UX, in contrast, amazon's UX is familiar and predictable. In our case, the use doesn't yet know what to expect.

- [ ] [+P2, CRITICAL] Add back button on the payment UX

**Comment by akshatbhargava123** [comment]
Okay @saumyakaran, adding the above point to the description only under `payment confirmation view`.
Also, the same for transaction state issue comment.

**Comment by saumyakaran** [comment]
@akshatbhargava123 Could you please add the ETA for incorporating the rest of the feedback here itself? It tends to slip away if not documented on some reliable source.
