### ISSUE TITLE
[FEATURE REQUEST] Display balance on account selection modal

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#91]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/40575379/93449581-8c6dc680-f8f2-11ea-887f-4e847329b24d.png)
Users lose context about the balances on their accounts after connecting wallet.

**Describe the solution you'd like**
It would be helpful to show my tokens on each account.

**Additional context**

- A feature requested by @siman

**Comment by sahilnanda1995** [comment]
feature added in recent merge

while connecting wallet:

![image](https://user-images.githubusercontent.com/41546731/100067832-bdbbc300-2e5c-11eb-906c-d4c8de0643ed.png)

on account change:

![image](https://user-images.githubusercontent.com/41546731/100067847-c4e2d100-2e5c-11eb-81e6-79e994faa75c.png)
