### ISSUE TITLE
[FEATURE REQUEST] UI should remember user's account selection for given session

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#92]
**Is your feature request related to a problem? Please describe.**
Every time I refresh the page, I need to reconnect my wallet an select my account again.

**Describe the solution you'd like**
UI should remember my account selection for a session until I close my browser at least.

**Additional context**

- A feature requested by @siman - also came up during internal discussions with the team

**Comment by sahilnanda1995** [comment]
feature added: remembers last selected network and account
